name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2 
        with:
          version: '5.15.2'
          tools: 'tools_qtcreator,4,qt.tools.qtcreator'
      
      - run: tree ../Qt
